#deploy and installing code 
- hosts: nginx
  become: yes
  tasks:
    - name: "apt-get update"
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: "install nginx"
      apt:
        name: ["nginx"]
        state: latest

    - name: Copy index.html to Nginx document root
      copy:
        src: /home/nagaraju/project-day-1/index.html  # Replace with the path to your local index.html file
        dest: /usr/share/html

    - name: Set correct permissions for index.html
      file:
        path: /usr/share/html
        mode: '0644'

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
